# safelist
branches:
  only:
      - /.*/

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - language: python
      python: 3.6
      dist: xenial
      before_cache:
      cache:
      before_install:
      script: |
        bash .ci/ci_check_commit.sh

    # ubuntu 16
    - language: java
      jdk: openjdk8
      os: linux
      dist: xenial
      sudo: required

    # ubuntu 16
    - language: java
      jdk: openjdk11
      os: linux
      dist: xenial
      sudo: required

    # ubuntu 18
    - language: java
      jdk: openjdk8
      os: linux
      dist: bionic
      sudo: required

    # ubuntu 18
    - language: java
      jdk: openjdk11
      os: linux
      dist: bionic
      sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - gradle wrapper
  - sudo apt-get -y install jq
  - mysql -u root --password="" < .ci/travis.sql
script: |
  bash .ci/ci_check.sh && bash .ci/ci_integration_check.sh
after_success:
    - bash <(curl -s https://codecov.io/bash)
