[service]
    address = '0.0.0.0'
    port = 8340
    sslKey = 'classpath:ssl.key'
    sslCert = 'classpath:ssl.crt'
    caCert = 'classpath:ca.crt'
    sslOn = false

[auth]
    # for issuing token
    name = 'org1'
    secret = '123456'
    expires = 600 # 10 min

[db]
    # for connect database
    url = 'jdbc:mysql://localhost:3306/test'
    username = 'jimmy'
    password = 'abc123'
